# -*- coding: utf-8 -*-
"""Tarea Lab7_2_SVM_LagunaJunin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZHvu_UeZUhg0QhiyZWNqVc9ZLsdvPlS

---
## 📝 Tarea — Clasificación supervisada de un glaciar peruano con SVM

Aplica el **mismo flujo de trabajo** de la sección 7, pero ahora sobre un **glaciar peruano**, usando SVM (en lugar de K-Means no supervisado de la tarea anterior).

**Glaciar sugerido:** Coropuna (Arequipa) — el mismo que usaste en la tarea de K-Means, para poder comparar ambos enfoques sobre la misma área. Puedes usar otro glaciar si lo prefieres (Pastoruri en Áncash, Quelccaya en Cusco, algún nevado de la Cordillera Vilcanota, etc.) — solo ajusta las coordenadas.

### Clases sugeridas para el glaciar

| Código | Clase |
|--------|-------|
| 0 | Agua (lagunas proglaciares) |
| 1 | Nieve / Hielo |
| 2 | Roca expuesta / morrena |
| 3 | Pastizal ralo (zonas bajas) |

### Pasos a seguir

1. **Definir el área de estudio** del glaciar (celda de partida más abajo, reutiliza las coordenadas de tu tarea de K-Means).
2. **Cargar y visualizar** un composito Sentinel-2 de época seca.
3. **Recolectar puntos de entrenamiento** (clic interactivo o predefinidos) para las 4 clases — recuerda **verificar visualmente** cada punto antes de entrenar.
4. **Extraer valores espectrales y normalizar** (igual que hicimos para la Laguna Junín).
5. **Entrenar al menos dos clasificadores SVM**: uno lineal y uno RBF (con y sin normalizar, para comparar igual que en la sección 7).
6. **Clasificar la imagen completa** y visualizar en el mapa con leyenda.
7. **Comparar con tu resultado de K-Means** (tarea anterior): ¿coinciden las clases? ¿Cuál te parece más confiable y por qué?

> **Pista clave:** la nieve/hielo es muy brillante en el visible y muy oscura en SWIR — un contraste fuerte que debería facilitar la separación con SVM lineal incluso sin kernel RBF.
"""

# ── Configuración: área de estudio del glaciar (misma que en la tarea de K-Means) ──
import ee, geemap
ee.Authenticate()
ee.Initialize(project='utec-ingambiental-01')  # <-- REEMPLAZA con tu Project ID ee-cmillanarancibia

# Glaciar Coropuna (Arequipa)
LON_MIN_G, LAT_MIN_G = -72.766883, -15.417441
LON_MAX_G, LAT_MAX_G = -72.508209, -15.65

area_glaciar = ee.Geometry.Rectangle([LON_MIN_G, LAT_MIN_G, LON_MAX_G, LAT_MAX_G])

composito_g = (
    ee.ImageCollection('NASA/HLS/HLSL30/v002')
    .filterBounds(area_glaciar)
    .filterDate('2025-05-01', '2025-09-30')
    #.filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 20))
    .select(['B2','B3','B4','B5','B6','B7'])
    .median()
    .clip(area_glaciar)
)
composito_g = composito_g.select(
    ['B2','B3','B4','B5','B6','B7'], ['Azul','Verde','Rojo','NIR','SWIR1','SWIR2']
)

Map_g = geemap.Map(basemap="Esri.WorldTopoMap")
Map_g.centerObject(area_glaciar, zoom=13)
Map_g.addLayer(composito_g, {'bands':['Rojo','Verde','Azul'],'min':0,'max':0.6}, 'Sentinel-2 — Glaciar')
Map_g

"""### Tu turno

Completa las celdas siguientes siguiendo el mismo patrón usado para la Laguna Junín (sección 7).
"""

# TU CÓDIGO AQUÍ — Paso 3: recolectar puntos de entrenamiento para las 4 clases del glaciar
# Pista: reutiliza el widget interactivo de la sección 7, o define puntos predefinidos
#        con ee.Feature(ee.Geometry.Point([lon, lat]), {'landcover': codigo})

import ipywidgets as widgets
from IPython.display import display
from ipyleaflet import Marker, AwesomeIcon

# ── Definiciones de clases ──
class_labels = {
    'Agua (lagunas proglaciares)': 0,
    'Nieve / Hielo': 1,
    'Roca expuesta / morrena': 2,
    'Pastizal ralo (zonas bajas)': 3
}

# Almacenamiento de puntos recopilados
collected_points = {v: [] for v in class_labels.values()}

# ── Menú desplegable ──
class_dropdown = widgets.Dropdown(
    options=list(class_labels.keys()),
    value='Agua (lagunas proglaciares)',
    description='Clase:',
    style={'description_width': 'initial'}
)

# ── Registro de salida ──
log_output = widgets.Output()

# ── Controlador de clics ──
def handle_map_click(**kwargs):
    if kwargs.get('type') == 'click':
        coords = kwargs.get('coordinates') # [lat, lon]
        lat, lon = coords[0], coords[1]
        current_class = class_labels[class_dropdown.value]
        collected_points[current_class].append((lon, lat))

        # Colores válidos en ipyleaflet: gray reemplaza a brown
        colors = {0: 'blue', 1: 'white', 2: 'gray', 3: 'green'}

        icon = AwesomeIcon(name='map-marker', marker_color=colors[current_class])
        marker = Marker(location=(lat, lon), icon=icon, draggable=False)

        # AGREGAR AL MAPA CORRECTO (Map_g)
        Map_g.add(marker)

        with log_output:
            total = sum(len(v) for v in collected_points.values())
            print(f"[{class_dropdown.value}] Punto añadido ({lon:.4f}, {lat:.4f}) | Total: {total} puntos")

# Registrar el controlador en Map_g
Map_g.on_interaction(handle_map_click)

botón_borrar = widgets.Button(description='Borrar todos los puntos', button_style='warning')

def on_clear(b):
    for k in collected_points:
        collected_points[k] = []
    with log_output:
        log_output.clear_output()
        print("Todos los puntos borrados.")

botón_borrar.on_click(on_clear)

print("Haz clic en el mapa para obtener puntos de entrenamiento.")
print("Selecciona una clase del menú desplegable y luego haz clic en las ubicaciones del mapa.\n")
display(widgets.HBox([class_dropdown, botón_borrar]))
display(log_output)

#  Convertir los puntos clicados en un ee.FeatureCollection
class_names = {0: 'Agua (lagunas proglaciares)',
               1: 'Nieve / Hielo',
               2: 'Roca expuesta / morrena',
                3: 'Pastizal ralo (zonas bajas)'}

features = []
for class_code, points in collected_points.items():
    for lon, lat in points:
        feat = ee.Feature(ee.Geometry.Point([lon, lat]), {'landcover': class_code})
        features.append(feat)

puntos = ee.FeatureCollection(features)

print("Training points collected:")
for class_code, points in collected_points.items():
    print(f"  {class_names[class_code]:15s}: {len(points)} points")
print(f"  {'TOTAL':15s}: {puntos.size().getInfo()} points")

# TU CÓDIGO AQUÍ — Paso 4: extraer valores espectrales y normalizar (z-score)
# Pista: reutiliza sampleRegions + reduceRegion(mean/stdDev), igual que con la Laguna Junín
# Convertir los puntos recopilados por el widget a una FeatureCollection de GEE

bandas = ['Azul', 'Verde', 'Rojo', 'NIR', 'SWIR1', 'SWIR2']

datos_entrenamiento = composito_g.select(bandas).sampleRegions(
    collection=puntos,
    properties=['landcover'],
    scale=30
).filter(ee.Filter.notNull(bandas))

means = composito_g.select(bandas).reduceRegion(
    reducer=ee.Reducer.mean(),
    geometry=area_glaciar,
    scale=30,
    maxPixels=1e9
)

stds = composito_g.select(bandas).reduceRegion(
    reducer=ee.Reducer.stdDev(),
    geometry=area_glaciar,
    scale=30,
    maxPixels=1e9
)

bandas_norm = [b + '_norm' for b in bandas]

composito_g_norm = ee.Image.cat([
    composito_g.select(b)
    .subtract(ee.Number(means.get(b)))
    .divide(ee.Number(stds.get(b)))
    .rename(b + '_norm')
    for b in bandas
])


datos_entrenamiento_norm = composito_g_norm.sampleRegions(
    collection=puntos,
    properties=['landcover'],
    scale=30
).filter(ee.Filter.notNull(bandas_norm))

# TU CÓDIGO AQUÍ — Paso 5: entrenar SVM lineal y RBF (con y sin normalizar)
# Pista: ee.Classifier.libsvm(kernelType=..., cost=..., gamma=...)

# 1. Entrenar SVM Lineal (datos crudos)
svm_lineal = ee.Classifier.libsvm(
    kernelType='LINEAR',
    cost=10
).train(
    features=datos_entrenamiento,
    classProperty='landcover',
    inputProperties=bandas
)

# 2. Entrenar SVM RBF (datos normalizados Z-Score)
svm_rbf = ee.Classifier.libsvm(
    kernelType='RBF',
    cost=10,
    gamma=0.01
).train(
    features=datos_entrenamiento_norm,
    classProperty='landcover',
    inputProperties=bandas_norm
)

# TU CÓDIGO AQUÍ — Paso 6: clasificar la imagen completa y visualizar con leyenda
# Pista: composito_g.classify(modelo) + geemap.Map().addLayer(...) + Map.add_legend(...)

clasi_lineal = composito_g.select(bandas).classify(svm_lineal)
clasi_rbf = composito_g_norm.classify(svm_rbf)


# 0: Agua (Azul), 1: Nieve/Hielo (Blanco), 2: Roca (Gris), 3: Pastizal (Verde)
paleta_glaciar = ['#1f78b4', '#ffffff', '#808080', '#7ec841']
etiquetas = [
    'Agua (lagunas proglaciares)',
    'Nieve / Hielo',
    'Roca expuesta / morrena',
    'Pastizal ralo (zonas bajas)'
]

Map_g = geemap.Map(basemap="Esri.WorldTopoMap")
Map_g.centerObject(area_glaciar, zoom=12)


Map_g.addLayer(composito_g, {'bands': ['Rojo', 'Verde', 'Azul'], 'min': 0, 'max': 0.6}, 'Imagen RGB — Glaciar')
Map_g.addLayer(clasi_lineal, {'min': 0, 'max': 3, 'palette': paleta_glaciar}, 'SVM Lineal (sin norm)')
Map_g.addLayer(clasi_rbf, {'min': 0, 'max': 3, 'palette': paleta_glaciar}, 'SVM RBF (normalizado)')


Map_g.add_legend(title='Cobertura Glaciar', keys=etiquetas, colors=paleta_glaciar)
display(Map_g)

# Calcular área por clase de cobertura
import pandas as pd

area_img = ee.Image.pixelArea().rename('area_m2').addBands(clasi_rbf.rename('Clases'))

stats_area = area_img.reduceRegion(
    reducer=ee.Reducer.sum().group(groupField=1, groupName='Clases'),
    geometry=area_glaciar,
    scale=30,
    maxPixels=1e9
)

class_names = {
    0: 'Agua (lagunas proglaciares)',
    1: 'Nieve / Hielo',
    2: 'Roca expuesta / morrena',
    3: 'Pastizal ralo (zonas bajas)'
}

grupos = stats_area.get('groups').getInfo()
filas = []

for g in grupos:
    cid = g['Clases']
    m2 = g['sum']
    filas.append({
        'ID': cid,
        'Clase': class_names.get(cid, f'Clase {cid}'),
        'Área (ha)': round(m2 / 10000.0, 2),
        'Área (km²)': round(m2 / 1000000.0, 2)
    })

df_areas = pd.DataFrame(filas)
display(df_areas)

"""### Para tu informe

Responde brevemente (puedes usar esta misma celda en formato Markdown):

1. ¿Qué kernel (lineal o RBF) dio un mapa más coherente para el glaciar? ¿Por qué crees que ocurrió eso?

El RBF (Radial Basis Function) utilizando las bandas normalizadas dio un mapa más coherente, porque en ambientes glaciares complejos existen gradientes de humedad, sombras topográficas y zonas de transición que generan solapamientos no lineales en la firma espectral. El kernel RBF mapea los datos a un espacio multidimensional donde traza fronteras de decisión curvas y flexibles, superando las limitaciones del kernel Lineal que intenta separar las clases mediante hiperplanos rectos y rígidos.

2. Compara el mapa de SVM con el de K-Means (tarea anterior, mismo glaciar). ¿Las clases de "nieve/hielo" coinciden espacialmente?

Coinciden en gran medida en el núcleo central del glaciar, ya que la nieve y el hielo limpio presentan una firma espectral muy distintiva.
Sin embargo, las mayores diferencias ocurren en los bordes glaciares, zonas con sombra o hielo con detritos. K-Means al no tener guía, tiende a confundir las sombras profundas con agua o a crear agrupaciones heterogéneas de morrena/hielo sucio, mientras que SVM clasifica mejor estas zonas de borde al basarse en los puntos de entrenamiento guiados. Aunque, también hay ciertas zonas que tiende a confundir.

3. ¿Qué ventaja tiene SVM (supervisado) sobre K-Means (no supervisado) para este problema? ¿Y qué desventaja?

Control y precisión temática. Al ser supervisado, impones desde el inicio las categorías de interés real con su correspondiente código numérico, asegurando que el modelo aprenda la variabilidad específica de clases difíciles como Roca expuesta/morrena frente a Pastizal ralo. Pero requiere trabajo manual previo para recolectar puntos representativos e interpretar el terreno. Si la muestra de entrenamiento es escasa, sesgada o no incluye alguna cobertura presente en la imagen, la clasificación de todo el mapa se degradará significativamente.
"""